services:
  # ---------- Backend ----------
  - type: web
    name: joblist-api
    env: node
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://job-list-refactor.onrender.com

  # ---------- Frontend ----------
  - type: static
    name: joblist-ui
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://job-list-87ft.onrender.com/api
