#!/usr/bin/env sh
BRANCH=$(git symbolic-ref --short HEAD)

if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
  echo "❌  Push direkt auf '$BRANCH' ist untersagt – bitte Pull Request benutzen."
  exit 1
fi

# alles ok
exit 0